/*
 * Nuertey Odzeyem, August 27, 2020
 * 
 * Usually autogenerated by the Meson build system, but since we dwell
 * on ARM Embedded and thus the Keil Studio and ARMCC build/compile 
 * system, baseline our version from that generated from Ubuntu 16.04.
 * Feel free to edit. Such capabilities can be used to exclude parts of
 * libparam that are not needed on embedded nor indeed would compile.
 */

#pragma once

#undef PARAM_HAVE_SYS_QUEUE

#undef PARAM_STORE_FILE

#undef PARAM_STORE_LOG

#undef PARAM_STORE_VMEM